server:
    port: 9000
    contextPath:

kafka:
    topic: si.topic
    newTopic: si.new.topic
    messageKey: si.key

spring:
    profiles:
        active: asb

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: org.sqlite.JDBC
      url: jdbc:sqlite:mb.db
      username: root
      password: root

    hibernate:
      dialect: com.infox.messagebook.utils.SQLiteDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400
logging:
    config: classpath:logback-spring.xml
    path: ./logs
    level: debug
cdcp :
    nodes :
      - ronnie
      - chloe



